import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import Footer from './components/footer/Footer'
import NavBar from './home/nav/NavBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'UNION',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <div className='flex flex-col min-h-screen'>
            <NavBar/>
            <main className='flex-grow'>{children}</main>
            <Footer/>
        </div>
        


          </body>
    </html>
  )
}
